<body>
    <div id="platforme-button-injection"  data-mage-init='{"button": {}}'></div>
    <script>
        <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
            $productData = json_encode($product->getData());
        ?>
        const productData = <?php echo $productData ?>;
        window.productData = productData;
    </script>
</body>
